server:
  port: 8087

spring:
  cloud:
    stream:
      bindings:
        input-event:
          destination: event
          binder: local_rabbit
          group: cloud
        output-event:
          destination: event
          binder: local_rabbit
          group: cloud
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: rabbitmq
                password: rabbitmq
                virtual-host: /